### ISSUE TITLE
Extend JSON representation of weather forecast to include temporal info.

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/bigsky#20]

**Comment by henlindemreed** [comment]
Potential flowchart to get us from data to trees all the way. I'm thinking the time array is a boolean array where each entry represents a time and whether that time is affected by the weather we're talking about.
<pre>
Individual hourly data**
	|
        V
List of weather objects	--------> For each weather type, generate sequence of affected hours
					                           |
					                           V
That's the sequence of times <--- What is the most important* weather type today
	|				                          |
	|				                          V
	|                          Find other weather that coincides timewise
        V                               /
Dominant weather(s) + Time Array <-----/
	|
        V
    CKY Tree
</pre>
*I think importance of weather can be summarized as roughly PRECIP > CLOUD > WIND > WATER VAPOR > CLEAR but also maybe we need to account for the relative probabilites of the things?
**Generating weather objects from hourly data should be relatively easy, but again probabilities will make things difficult, also figuring out what the thresholds between something like 'heavy' and 'moderate' clouds. Also I think there is some importance logic that would need to go here too

ps hope you like my asciiart!

**Comment by mhrmm** [comment]
A couple options for the JSON:

        # a weather event looks like: 
        #  {'time': {'start': 6, 'end': 10, 'now': 3},
        #   'weather': [{'type': 'cloud', 'degree': 'heavy', 'probability': 'high', 'measure': 'N/A', 'snow_chance': False}]}
        #
        # a weather event looks like: 
        #  {'now': 3,
        #   'forecasts':
        #      [{'time': {'start': 6, 'end': 10, 'now': 3},
        #
